### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DarkReaper231** [parisolab/mathmod#170]
It would be really cool if MathMod could convert some basic obj files into MathMod scripts. Some models require a lot of math and really complex scripting so it would be nice if this process could be somewhat automated by creating desired shape in modeling software and then using MathMod to convert it into mathematical function.

**Comment by parisolab** [comment]
I don't think it's feasible to convert complex meshes with hundreds and thousands of vertex into practical mathematical description (like spline approximation for example). What can be done is to turn simple mathematical objects into complex ones with scale/bend/twist/... operations. K3DSurf (MathMod's predecessor) had already some tools to accomplish this and MathMod will be able to do the same in the near future.
