### ISSUE TITLE
Cannot find font directory

### ISSUE THREAD

**Issue by kmare** [parisolab/mathmod#181]
It seems like the latest 11.0 release for linux x86_64 has a hardcoded font directory path. I'm getting this error when running it:

```
Requesting 3.3 core context
QFontDatabase: Cannot find font directory /home/abderrahman/Desktop/Qt/5.9.5/Src/qtbase/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/abderrahman/Desktop/Qt/5.9.5/Src/qtbase/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/abderrahman/Desktop/Qt/5.9.5/Src/qtbase/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/abderrahman/Desktop/Qt/5.9.5/Src/qtbase/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
```

**Comment by parisolab** [comment]
> It seems like the latest 11.0 release for linux x86_64 has a hardcoded font directory path. I'm getting this error when running it:
> 
> ```
> Requesting 3.3 core context
> QFontDatabase: Cannot find font directory /home/abderrahman/Desktop/Qt/5.9.5/Src/qtbase/lib/fonts.
> Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
> QFontDatabase: Cannot find font directory /home/abderrahman/Desktop/Qt/5.9.5/Src/qtbase/lib/fonts.
> Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
> QFontDatabase: Cannot find font directory /home/abderrahman/Desktop/Qt/5.9.5/Src/qtbase/lib/fonts.
> Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
> QFontDatabase: Cannot find font directory /home/abderrahman/Desktop/Qt/5.9.5/Src/qtbase/lib/fonts.
> Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for example) or switch to fontconfig.
> ```

Hi, 
Have you tried the steps mentioned in the Readme.txt file? The font directory is integrated in the zip file.
To run MathMod, open a command line terminal:
1) cd mathmod-11.0-Linu64-static
2) ./RunMathMod.sh &
or
2) sh RunMathMod.sh &

If step (2) didn't work, try :

1) sudo ./RunMathMod.sh
2) chmod +x RunMathMod.sh
3) ./RunMathMod.sh

**Comment by kmare** [comment]
Oooops, I'm sorry. I ran the binary instead of the sh script! It's working perfectly, thank you so much for the hard work!

**Comment by parisolab** [comment]
You're welcome!
