### ISSUE TITLE
Does Mathmod draw a 3D implicit surface with more conditions?

### ISSUE THREAD

**Issue by justonlyasy** [parisolab/mathmod#187]
Assume that, I have this function
![image](https://user-images.githubusercontent.com/52594258/113901188-cce25280-97f8-11eb-8562-8fb045651c93.png)
How can I write its formulas in Mathmod?

**Comment by parisolab** [comment]
Yes MathMod can draw multiple conditions and this can achieved in many ways with either "*", min/max functions , "&" and "!" operator... For more informations, please refer to MathMod supported operators and mathematical functions: https://github.com/parisolab/mathmod/wiki/documentation#SupportedOperatorsFunctions
Also, please be advised that this board is only for  MathMod bugs report and users pull requests.

**Comment by justonlyasy** [comment]
Thanks for your reply! I will notice this.
