### ISSUE TITLE
Which is the last version to support Qt4?

### ISSUE THREAD

**Issue by barracuda156** [parisolab/mathmod#243]
It is nowhere obvious, and even the current code implies that Qt4 should work, otherwise this line makes no sense: https://github.com/parisolab/mathmod/blob/24d03a04c17363520ae7cf077e72a7b8684eb6fd/MathMod.pro#L59-L61

However, the build of 11.1 fails, and even 9.1 fails too.

@parisolab Could you please say which version I should use?

**Comment by barracuda156** [comment]
After fixing some errors with v. 9.0, stuck on this:
```
In file included from ui_modules/drawingoptions.h:26,
                 from main.cpp:24:
./ui_drawingoptions.h: In member function ‘void Ui_DrawingOptions::setupUi(QMainWindow*)’:
./ui_drawingoptions.h:733: error: ‘class QPushButton’ has no member named ‘setToolTipDuration’
./ui_drawingoptions.h:749: error: ‘class QPushButton’ has no member named ‘setToolTipDuration’
./ui_drawingoptions.h:917: error: ‘class QTabWidget’ has no member named ‘setTabBarAutoHide’
./ui_drawingoptions.h:4273: error: ‘ImhMultiLine’ is not a member of ‘Qt’
./ui_drawingoptions.h:4278: error: ‘class QTextEdit’ has no member named ‘setSizeAdjustPolicy’
./ui_drawingoptions.h:4278: error: ‘AdjustToContents’ is not a member of ‘QAbstractScrollArea’
./ui_drawingoptions.h: In member function ‘void Ui_DrawingOptions::retranslateUi(QMainWindow*)’:
./ui_drawingoptions.h:4753: error: ‘class QComboBox’ has no member named ‘setCurrentText’
./ui_drawingoptions.h:4761: error: ‘class QComboBox’ has no member named ‘setCurrentText’
make: *** [main.o] Error 1
```

**Comment by barracuda156** [comment]
Looks like at least partly this was breaking: https://github.com/parisolab/mathmod/commit/fc99dd99636b9d043a8caea1980b93ae56fa7dd2

**Comment by barracuda156** [comment]
With quite some effort I was able to get v. 7 build with Qt4 running:

![mathmod](https://github.com/parisolab/mathmod/assets/92015510/2e423aa4-e51f-4a7e-80d7-ed7949564da8)

**Comment by parisolab** [comment]
Hi,You can also try to install compiled MathMod versions for MacOS that comes with the necessary QT lib :https://sourceforge.net/projects/mathmod/files/
Regards,Abderrahman TahaMathMod/K3DSurf developer


    On Thursday, July 4, 2024 at 04:56:30 a.m. EDT, Sergey Fedorov ***@***.***> wrote:  
 
 


With quite some effort I was able to get v. 7 build with Qt4 running:

mathmod.png (view on web)

**Comment by barracuda156** [comment]
@parisolab Thank you for responding.

There are two reasons to go with building from source:

1. I am making a port for MacPorts, and building from source is a requirement.
2. I suspect there are no prebuilt binaries for PowerPC, which is also of interest.

**Comment by barracuda156** [comment]
We got it merged to MacPorts: https://ports.macports.org/port/mathmod/details (app version will be picked according to the OS version)

**Comment by parisolab** [comment]
> We got it merged to MacPorts: https://ports.macports.org/port/mathmod/details (app version will be picked according to the OS version)

Thank you for the hard work you put into making this port!
