### ISSUE TITLE
OpenGL ES port for ARM platforms such as Raspberry Pi

### ISSUE THREAD

**Issue by sandrobilbeisi** [parisolab/mathmod#32]
Hello

I'm trying to build MathMod for the Raspberry Pi platform .

I haven't been able to coerce the build to OpenGL ES via 
http://doc.qt.io/qt-5/qopenglfunctions.html

I get a gazillions incomprehensible errors .

has anyone else tried to build targeting OpenGL ES ?

**Comment by parisolab** [comment]
Hi,
I've successfully build and run MathMod under Raspberry Pi 4 with Manjaro OS.
It's a full fledged Linux 64 OS though so the source code don't to support OpengL ES.
https://manjaro.org/download/#
![Manjaro](https://user-images.githubusercontent.com/38238160/70587582-51d34280-1b98-11ea-9694-53310d78af32.png)

**Comment by parisolab** [comment]
![Screenshot_2019-12-11_00-22-20](https://user-images.githubusercontent.com/38238160/70594181-b4830900-1bad-11ea-8543-fc5d3e4baff7.png)
