### ISSUE TITLE
Mix of parametric and IsoSurfaces in one Modell not possible

### ISSUE THREAD

**Issue by JHenneberg** [parisolab/mathmod#81]
Hello,
thanks for this greate software. I am trying to mix parametric and isosurface in one modell but it seems it is not possible. Is this intended?

```JSON
{
    "MathModels": [
        {
            "Param3D": {
                "Component": [
                    "paraSurf1_01",
                    "paraSurf2_01"
                ],
                "Fx": [
                    "10*v-5",
                    "6*(u-u^2+v-v^2)"
                ],
                "Fy": [
                    "10*u-5",
                    "10*u-5"
                ],
                "Fz": [
                    "6*(u-u^2+v-v^2)",
                    "10*v-5"
                ],
                "Name": [
                    "Surfaces1"
                ],
                "Umax": [
                    "1",
                    "1"
                ],
                "Umin": [
                    "0",
                    "0"
                ],
                "Vmax": [
                    "0.8",
                    "1"
                ],
                "Vmin": [
                    "0",
                    "0.5"
                ]
            }
        },
        {
            "Iso3D": {
                "Component": [
                    "ImpSurf1"
                ],
                "Fxyz": [
                    "(x-2)^4+y*4-2^4"
                ],
                "Name": [
                    "Surfaces2"
                ],
                "Xmax": [
                    "8.2"
                ],
                "Xmin": [
                    "-8.2"
                ],
                "Ymax": [
                    "8.2"
                ],
                "Ymin": [
                    "-8.2"
                ],
                "Zmax": [
                    "4"
                ],
                "Zmin": [
                    "-4"
                ]
           }
        }
    ]
}

````

**Comment by parisolab** [comment]
Hi,
Yes, right now MathMod can't render parametric  and isosurfaces at once. It can only render models including multiple surfaces with the same definition type (ie: parametric or isosurfaces). However, this feature was tested successfully some time ago so it won't take too long to be added but not in the next forthcoming release v10.0

**Comment by JHenneberg** [comment]
Ok sounds good. Thanks for the fast feedback.

**Comment by parisolab** [comment]
An early preview of MathMod ability to Mix parametric and IsoSurfaces
![Screen Shot 2019-12-21 at 2 34 19 AM](https://user-images.githubusercontent.com/38238160/71304900-ab0e5380-239a-11ea-8e10-a107a23a86ca.png)

**Comment by parisolab** [comment]
Partial support now complete.  An example of scripts showing iso and parametric surfaces side by side:
![Screen Shot 2020-01-04 at 4 54 52 AM](https://user-images.githubusercontent.com/38238160/71763858-fbafa180-2eae-11ea-94c7-32da1f790000.png)

{
"ParIso": [
{
    "Param3D": {
        "Component": [
            "BlobbyTorus"
        ],
        "Description": [
            "Blobby Torus by Abderrahman Taha 07/10/2019"
        ],
        "Funct": [
            "G1=(8+(sin(2*(u-v+t+sin(v-u)))+3)*cos(u))*cos(v)",
            "G2=(8+(sin(2*(u-v+t+sin(v-u)))+3)*cos(u))*sin(v)",
            "G3=((sin(2*(u-v+t+sin(v-u)))+3)*sin(u))"
        ],
        "Grid": [
            "200",
            "200"
        ],
        "Fx": [
            "-G1(u,v,t)+20"
        ],
        "Fy": [
            "G2(u,v,t)-10"
        ],
        "Fz": [
            "G3(u,v,t)"
        ],
        "Name": [
            "Blobby_Torus"
        ],
        "Umax": [
            "2*pi"
        ],
        "Umin": [
            "0"
        ],
        "Vmax": [
            "2*pi"
        ],
        "Vmin": [
            "0"
        ]
    },
    "Texture": {
        "Colors": [
            "R= if((abs(7*u)%pi/2& abs(7*v)%pi/3),(6/10),1) ",
            "G= if((abs(7*u)%pi/2| abs(7*v)%pi/3),(8/10),(4/10)) ",
            "B= if((abs(7*u)%pi/2| abs(7*v)%pi/3),(6/10),(1/10)) ",
            "T=1"
        ],
        "Name": "Candy",
        "Noise": "1"
    }
}
,
{
    "Iso3D": {
        "Component": [
            "Sphere",
            "Cube",
            "Schwarz",
            "Sinus"
        ],
        "Funct": [
            "Radius=sqrt(x*x+y*y+z*z)",
            "Theta=atan(y/x)",
            "Phi=acos(z/sqrt(x*x+y*y+z*z))"
        ],
        "Fxyz": [
            "x*x+y*y+z*z-36",
            "(x+14)^100+y^100+z^100-6*10^77",
            "cos(2*x/3)+cos((y+16)*2/3)+cos(2*z/3)",
            "sin(2*pi*(((x+14)/4)^2+((y+14)/4)^2))/8+z/4"
        ],
        "Name": [
            "CheckerTexture"
        ],
        "Grid": [
            "200",
            "200",
            "200",
            "200"
        ],
        "Xmax": [
            "6",
            "-8",
            "6",
            "-9"
        ],
        "Xmin": [
            "-6",
            "-20",
            "-6",
            "-19"
        ],
        "Ymax": [
            "6",
            "6",
            "-10",
            "-9"
        ],
        "Ymin": [
            "-6",
            "-6",
            "-22",
            "-19"
        ],
        "Zmax": [
            "6",
            "6",
            "6",
            "4"
        ],
        "Zmin": [
            "-6",
            "-6",
            "-6",
            "-4"
        ]
    },
    "Texture": {
        "Colors": [
            "R=(int(abs(x))+int(abs(y))+int(abs(z)))%2",
            "G=1/10",
            "B=1",
            "T=1"
        ],
        "Name": "Checker"
    }}
]
}

**Comment by parisolab** [comment]
Preview of MathMod support for a pariso (parametrics/isosurfaces) object undergoing the morph and animation (rotations) effects.
Also, each component from the pariso object can have it's own defined textures, condition (cnd) function:
https://www.facebook.com/parisolab/videos/594074478071764/
